// Dummy data for the application

export const vehicleCategories = [
  { id: "suv", name: "SUV", icon: "🚙" },
  { id: "sedan", name: "Sedan", icon: "🚗" },
  { id: "hatchback", name: "Hatchback", icon: "🚕" },
  { id: "van", name: "Van", icon: "🚐" },
  { id: "luxury", name: "Luxury", icon: "🏎️" },
];

export const vehicles = [
  {
    id: "1",
    name: "BMW X5",
    category: "suv",
    pricePerDay: 120,
    image: "/placeholder.svg",
    rating: 4.8,
    reviews: 124,
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    features: ["GPS", "Bluetooth", "AC", "Leather Seats"],
    available: true,
  },
  {
    id: "2",
    name: "Mercedes-Benz C-Class",
    category: "sedan",
    pricePerDay: 100,
    image: "/placeholder.svg",
    rating: 4.9,
    reviews: 98,
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    features: ["GPS", "Sunroof", "AC", "Premium Audio"],
    available: true,
  },
  {
    id: "3",
    name: "Toyota Corolla",
    category: "sedan",
    pricePerDay: 60,
    image: "/placeholder.svg",
    rating: 4.6,
    reviews: 210,
    seats: 5,
    transmission: "Automatic",
    fuelType: "Hybrid",
    features: ["GPS", "Bluetooth", "AC"],
    available: true,
  },
  {
    id: "4",
    name: "Honda Civic",
    category: "hatchback",
    pricePerDay: 55,
    image: "/placeholder.svg",
    rating: 4.5,
    reviews: 156,
    seats: 5,
    transmission: "Manual",
    fuelType: "Petrol",
    features: ["Bluetooth", "AC"],
    available: true,
  },
  {
    id: "5",
    name: "Ford Transit",
    category: "van",
    pricePerDay: 90,
    image: "/placeholder.svg",
    rating: 4.7,
    reviews: 89,
    seats: 12,
    transmission: "Manual",
    fuelType: "Diesel",
    features: ["GPS", "AC", "Cargo Space"],
    available: true,
  },
  {
    id: "6",
    name: "Audi A8",
    category: "luxury",
    pricePerDay: 180,
    image: "/placeholder.svg",
    rating: 5.0,
    reviews: 67,
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    features: ["GPS", "Massage Seats", "Premium Audio", "Sunroof", "Leather Interior"],
    available: true,
  },
  {
    id: "7",
    name: "Tesla Model 3",
    category: "sedan",
    pricePerDay: 110,
    image: "/placeholder.svg",
    rating: 4.9,
    reviews: 143,
    seats: 5,
    transmission: "Automatic",
    fuelType: "Electric",
    features: ["Autopilot", "Premium Audio", "Glass Roof"],
    available: false,
  },
  {
    id: "8",
    name: "Range Rover Sport",
    category: "suv",
    pricePerDay: 150,
    image: "/placeholder.svg",
    rating: 4.8,
    reviews: 92,
    seats: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    features: ["GPS", "4WD", "Leather Seats", "Premium Audio"],
    available: true,
  },
];

export const bookings = [
  {
    id: "B001",
    userId: "U001",
    vehicleId: "1",
    startDate: "2025-01-15",
    endDate: "2025-01-20",
    status: "confirmed",
    totalPrice: 600,
    pickupLocation: "Downtown Office",
    dropoffLocation: "Airport Terminal 1",
  },
  {
    id: "B002",
    userId: "U001",
    vehicleId: "3",
    startDate: "2024-12-10",
    endDate: "2024-12-15",
    status: "completed",
    totalPrice: 300,
    pickupLocation: "Airport Terminal 2",
    dropoffLocation: "Hotel Grand Plaza",
  },
  {
    id: "B003",
    userId: "U002",
    vehicleId: "6",
    startDate: "2025-02-01",
    endDate: "2025-02-05",
    status: "pending",
    totalPrice: 720,
    pickupLocation: "City Center",
    dropoffLocation: "Beach Resort",
  },
];

export const users = [
  {
    id: "U001",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1234567890",
    profileImage: "/placeholder.svg",
    joinDate: "2024-01-15",
    totalBookings: 12,
    status: "active",
  },
  {
    id: "U002",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+1234567891",
    profileImage: "/placeholder.svg",
    joinDate: "2024-03-20",
    totalBookings: 8,
    status: "active",
  },
];

export const drivers = [
  {
    id: "D001",
    name: "Michael Johnson",
    email: "michael.j@example.com",
    phone: "+1234567892",
    licenseNumber: "DL123456789",
    profileImage: "/placeholder.svg",
    rating: 4.9,
    totalTrips: 156,
    status: "active",
    available: true,
  },
  {
    id: "D002",
    name: "Sarah Williams",
    email: "sarah.w@example.com",
    phone: "+1234567893",
    licenseNumber: "DL987654321",
    profileImage: "/placeholder.svg",
    rating: 4.8,
    totalTrips: 142,
    status: "active",
    available: false,
  },
];

export const reviews = [
  {
    id: "R001",
    userId: "U001",
    vehicleId: "1",
    rating: 5,
    comment: "Excellent vehicle! Smooth drive and great service.",
    date: "2024-12-01",
  },
  {
    id: "R002",
    userId: "U002",
    vehicleId: "3",
    rating: 4,
    comment: "Good car for the price. Would recommend.",
    date: "2024-11-28",
  },
  {
    id: "R003",
    userId: "U001",
    vehicleId: "6",
    rating: 5,
    comment: "Luxury at its finest! Amazing experience.",
    date: "2024-12-15",
  },
];

export const adminStats = {
  totalUsers: 2847,
  totalDrivers: 156,
  totalVehicles: 234,
  totalBookings: 1823,
  monthlyRevenue: 186540,
  activeBookings: 89,
};
